### ISSUE TITLE
ETH client cannot get block due to wrong header hash on mumbai testnet

### ISSUE THREAD

**Issue by kitty-swap** [maticnetwork/bor#387] opened 2022-05-09 04:24 UTC
#### System information

Geth version: v1.10.12
OS & Version: Mac
Commit hash : (if `develop`)

#### Expected behaviour
ETH client should be able to get all blocks on mumbai testnet

#### Actual behaviour
ETH client fails to get block `26261184` on mumbai testnet because its header hash is equal empty root hash. 

ETH client has [a check](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L128) to see if the header hash is equivalent to empty root hash and the transaction list is empty. However, in the case of block `26261184`, the header hash is empty while the transaction list is non-empty and hence the ETH throws an error. 

This seems to be a serious error if the header hash is equivalent to empty root hash while the transaction list is empty. 

Web3, however, is able to get the block details. Here's the output when running `web3.eth.getBlock(26261184)` 

```
{
  baseFeePerGas: '0x7',
  difficulty: '5',
  extraData: '0xd682021083626f7288676f312e31382e31856c696e75780000000000000000003964cda17b626063918e470b4b7da276faae614a52807bca1e05e996053d51187609e8223052f52c63c89217e8599d85269cfdc38b7c24ab118bdf805905c79e01',
  gasLimit: '0x1312d00',
  gasUsed: '0x0',
  hash: '0x8b0a3b5258941fd68588b8ca7a625a865769f93acd7b33b500cb403f14ee6f1e',
  logsBloom: ....
  miner: '0x0000000000000000000000000000000000000000',
  mixHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  nonce: '0x0000000000000000',
  number: 26261184,
  parentHash: '0x16f92fd77b97f435cf0f16efe1c2af957cad05eba7dc292bb461cfb61b34f7f2',
  receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  size: 612,
  stateRoot: '0xcadf042db0e46f73462afdb795b763af714f84c02293a2d2db86ca8f191ae332',
  timestamp: 1652059672,
  totalDifficulty: '181779452',
  transactions: [
    '0xf83ea6c184ee0e09b6dfe9ea5b3f37630aa1133545318be05002ffa9502b3f63'
  ],
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  uncles: []
}
```

#### Steps to reproduce the behaviour
1. Try to get block `26261184` on mumbai testnet with ETH client. 
```
client.BlockByNumber(context.Background(), big.NewInt(height))
```
2. The request fails and returns an error `server returned non-empty transaction list but block header indicates no transactions`

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by temaniarpit27** [comment] 2022-06-08 08:57
Please use the latest bor version
Closing this for now.
Reopen if required

**Comment by ggarri** [comment] 2022-11-23 13:56
hi @temaniarpit27, we encountered the very same issue, which seems to be related to the fact Polygon is building blocks with invalid transactions in it, such it is the case for this [block](https://polygonscan.com/block/35936768) along with this [tx](https://polygonscan.com/txs?block=35936768) where the `from` and `to` values are set to null so that when block [body is unmarshaled](https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L124) it does not attach any tx to the transaction list.

I tried to use your ethclient version to go away from this situation in a clean manner but the fact your repo uses the same go-ethereum module as official geth library, which is also used in our project, limited its usage. 

I was wondering if you provide any context on why Polygon is generating invalid evm transaction for this "empty" blocks in your chain and whether or not you are researching any alternative for it which makes your chain fully evm compatible  .

**Comment by markya0616** [comment] 2022-12-13 15:47
same after upgrading version to v0.3.1-mumbai.
https://github.com/maticnetwork/bor/releases/tag/v0.3.1-mumbai

**Comment by manav2401** [comment] 2022-12-13 19:57
Hi, we're not generating invalid EVM transactions. Those are state sync transactions which are done every sprint by bor and they perform direct state transition by applying all the state sync events (bridge events sent by heimdall) in a single transaction and sets the `to` and `from` field to `0x00`. You can read more about it over [here](https://wiki.polygon.technology/docs/category/state-sync). 

Thanks for reporting this issue and mentioning the steps to reproduce it. I've confirmed that it exists but only partially. It would only throw an error where there's just 1 state-sync transaction and no other additional (normal) transaction. In any other case (like for block 29652208), it'd return correct results. 

At the moment, you'd need to rely on the RPC endpoints to provide the data for such blocks. We'd try to incorporate a fix in our eth client package in the next release. Also, just a suggestion, you can also modify the eth client by your own and consume for internal use. Closing this for now. Feel free to re-open if required. Thanks!

**Closed by manav2401** 2022-12-13 19:57 UTC

**Comment by manav2401** [comment] 2022-12-14 06:01
Yes, we're aware of that and we've already accounted the change of removal of miner address (from RPC call) and just return 0x00 as it was returned previously. This will be available in the next patch for mumbai. Thanks!

**Comment by visopsys** [comment] 2022-12-27 01:37
I don't know if you guys fix this but this happens for a very recent block `30187616`. It also happens for `30146592`

**Comment by manav2401** [comment] 2022-12-29 06:01
Hey @visopsys, as the releases and tags were planned/fixed long time ago, we could not incorporate this change at the moment. It will be available in the next release (which is v0.3.3). 

Moreover, regarding the return of "0x00" as miner, that change has been incorporated in v0.3.2-beta only for mumbai testnet as of now (see [this](https://forum.polygon.technology/t/bor-mumbai-upgrade-v0-3-2-beta-patch-for-v0-3-1-mumbai-action-required/10750)).

**Comment by 0xsharma** [comment] 2023-01-11 13:13
Hey @visopsys @kitty-swap @markya0616 , please use bor eth-client when running with Polygon-POS chain. This check ( where this error originates ) is removed from the code. 

Thank you 💜

**Comment by charalarg** [comment] 2024-03-12 17:42
@0xsharma Is this check added again on purpose on [this](https://github.com/maticnetwork/bor/commit/b343cffdb4bec2f0f91141193c280ae3acb0f1b3) commit?

**Comment by 0xsharma** [comment] 2024-03-13 07:23
No @charalarg , this check is not added back again.

**Comment by charalarg** [comment] 2024-03-13 07:49
@0xsharma But I can see that check [here](https://github.com/maticnetwork/bor/blob/master/ethclient/ethclient.go#L154), am I missing somehting?

**Comment by charlie-paxos** [comment] 2024-04-16 19:16
Hey @0xsharma, bumping as I'm also interested here- it does seem like the check is back in the [eth-client code](https://github.com/maticnetwork/bor/blob/master/ethclient/ethclient.go#L165). Is that intentional?
