### ISSUE TITLE
Missing receipts data eth_getTransactionReceipt

### ISSUE THREAD

**Issue by quick-pawiromitchel** [maticnetwork/bor#1345] opened 2024-10-07 12:18 UTC
#### **System information**

Bor client version:
```
Version: 1.5.0-beta2
GitCommit: c8c83116bee5b6f3d39107a3814125a7f03cc0c7
```

Heimdall client version: `1.0.9-beta`

OS & Version: Linux

Environment: Polygon Amoy

Type of node: Full node

#### **Overview of the problem**

Please describe the issue you experiencing.
`eth_getTransactionReceipt` returns `null` for txs that shouldn't be missing
- 0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919
- 0x1311556f56b90208365612877af78f55e7f47a026a931270bc57a0c7c98eb678

#### **Reproduction Steps**

Please mention the steps required to reproduce this issue. 
This is the payload
```
{"method":"eth_getTransactionReceipt","params":["0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919"],"id":1,"jsonrpc":"2.0"}
```

Returns 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}
```

But block receipts do work 
`{"method":"eth_getBlockReceipts","params":["0xc2b43b"],"id":1,"jsonrpc":"2.0"}`

As you can see, the txhash is in the response, but `eth_getTransactionReceipt` returns `null` 
![image](https://github.com/user-attachments/assets/9697c250-8d1a-445e-9e07-4f8b3c6164e0)

**Comment by cffls** [comment] 2024-10-07 15:00
Hi @quick-pawiromitchel , thanks for reporting this issue. Unfortunately, I am not able to reproduce this issue.

With bor `v1.5.0-beta2`, I was able to query this transaction. See log below. Did the node return non-empty result after rolling back to `v1.4.1`?

```
bor version
Version: 1.5.0-beta2
GitCommit: c8c83116bee5b6f3d39107a3814125a7f03cc0c7

curl http://localhost:8545   -X POST   -H "Content-Type: application/json" --data '{"method":"eth_getTransactionReceipt","params":["0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919"],"id":1,"jsonrpc":"2.0"}' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3022    0  2881  100   141  1941k  97308 --:--:-- --:--:-- --:--:-- 2951k
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0xfe99317cc8f618c933dc644dd5bbe8ba2badf6fc3cf2c0c01d473ca825ba8b68",
    "blockNumber": "0xc2b43b",
    "contractAddress": null,
    "cumulativeGasUsed": "0x5208",
    "effectiveGasPrice": "0xc393e6d00",
    "from": "0x985e131a7527ac26bac55003eb720f077cd16f71",
    "gasUsed": "0x5208",
    "logs": [
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0xe6497e3ee548a3372136af2fcb0696db31fc6cf20260707645068bd3fe97f3c4",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x000000000000000000000000985e131a7527ac26bac55003eb720f077cd16f71",
          "0x000000000000000000000000d8d1d89b2609203e1075629188e28234c7008aa8"
        ],
        "data": "0x00000000000000000000000000000000000000000000000000d529ae9e8600000000000000000000000000000000000000000000000000002e2dafd72b711c2c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002d5886288ceb1c2c00000000000000000000000000000000000000000000000000d529ae9e860000",
        "blockNumber": "0xc2b43b",
        "transactionHash": "0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919",
        "transactionIndex": "0x0",
        "blockHash": "0xfe99317cc8f618c933dc644dd5bbe8ba2badf6fc3cf2c0c01d473ca825ba8b68",
        "logIndex": "0x0",
        "removed": false
      },
      {
        "address": "0x0000000000000000000000000000000000001010",
        "topics": [
          "0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
          "0x0000000000000000000000000000000000000000000000000000000000001010",
          "0x000000000000000000000000985e131a7527ac26bac55003eb720f077cd16f71",
          "0x000000000000000000000000ac75d6efec891724b88b916b36e2ef38bcbec73f"
        ],
        "data": "0x0000000000000000000000000000000000000000000000000003eab7c8d899880000000000000000000000000000000000000000000000002e4056b00c833c2c0000000000000000000000000000000000000000000001e4025bf1d3c55e91620000000000000000000000000000000000000000000000002e3c6bf843aaa2a40000000000000000000000000000000000000000000001e4025fdc8b8e372aea",
        "blockNumber": "0xc2b43b",
        "transactionHash": "0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919",
        "transactionIndex": "0x0",
        "blockHash": "0xfe99317cc8f618c933dc644dd5bbe8ba2badf6fc3cf2c0c01d473ca825ba8b68",
        "logIndex": "0x1",
        "removed": false
      }
    ],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000008000000000000000000000000000000000000000000000000000000000800000000000000100000100200000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000200008000000000000000000000000000020000000000100000000000000004000000000000000000001000000000000000000000000800000108000000000000000000000000000000000000800000000000000000000800000000500100000",
    "status": "0x1",
    "to": "0xd8d1d89b2609203e1075629188e28234c7008aa8",
    "transactionHash": "0x3e718fe3773f0c23003a7507c0a808d9a8e04eb529570ada0320061bf7d45919",
    "transactionIndex": "0x0",
    "type": "0x2"
  }
}
```

**Comment by cffls** [comment] 2024-10-10 19:19
This was due to the `txLookupLimit` incorrectly configured on start. Fixed in https://github.com/maticnetwork/bor/commit/48bdfa7ffbfb8da50fbc3bbef54882d3b80e698f.

**Closed by cffls** 2024-10-10 19:19 UTC
