### ISSUE TITLE
eth_getLogs not showing state sync logs

### ISSUE THREAD

**Issue by 0xabhinav** [maticnetwork/bor#432] opened 2022-06-15 12:45 UTC
#### System information

Geth version: `0.2.16-stable`
OS & Version: Ubuntu Server 20.04

#### Expected behaviour
`eth_getLogs` should include logs for state sync txns

#### Actual behaviour
State sync txns are not returned

#### Steps to reproduce the behaviour
Using bor's embedded js:-
```
> eth.getLogs({fromBlock: '0x126d3c0', toBlock: '0x126d3c0'});
...
....
{
    address: "0x0000000000000000000000000000000000001010",
    blockHash: "0xa6252b0d4bf8fba5a6511bef9b51771cc2e76f048fd4a290a8a2619908c4111d",
    blockNumber: "0x126d3c0",
    data: "0x00000000000000000000000000000000000000000000000000132fc36fe662000000000000000000000000000000000000000000000000002cca131ba828a5b30000000000000000000000000000000000000000000008d838fe0aa089e30dc20000000000000000000000000000000000000000000000002cb6e358384243b30000000000000000000000000000000000000000000008d839113a63f9c96fc2",
    logIndex: "0x221",
    removed: false,
    topics: ["0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63", "0x0000000000000000000000000000000000000000000000000000000000001010", "0x000000000000000000000000f6f28dc06989611e10df1eed4b94c94206dc96c4", "0x0000000000000000000000007b5000af8ab69fd59eb0d4f5762bff57c9c04385"],
    transactionHash: "0x47317951f41257fb3f7253377a35de1c8beb64676f457a301e031c6ed1eb6d67",
    transactionIndex: "0x121"
}]
```
Notice the last log index -> "0x221" -> 545 which is just before the state sync tx as seen on [polygonscan](https://polygonscan.com/tx/0xe377029ac8a2d6c0c0917feba2ea064f3f34dc3da232ab2a4fa6aa50035ecd62#eventlog)

Note: The issue seems similar to #369, just on a difference rpc endpoint.

**Comment by ssandeep** [comment] 2022-06-28 20:14
Hello @0xabhinav, 

We have received a few bug reports around missed state sync transactions in a few RPC calls for old blocks (before December 2021). The root cause of the issue was an unhandled code flow (during chain rewinds) to insert logs into the table.

Please note that this didn’t affect consensus; hence, the chain data is unaffected. The issue was resolved in the upstream Geth codebase and has been available since Bor versions that were released after Dec 2021. Therefore, there are no missing state sync transactions in blocks created after that.

If you are facing any issues retrieving old state sync transactions data, we recommend using the latest snapshot from [https://snapshots.matic.today/](https://snapshots.matic.today/). We worked on backfilling all missing data and created snapshots from such nodes.

▶️ To use the last **snapshot**, please follow the steps - [https://forum.polygon.technology/t/snapshot-instructions-for-heimdall-and-bor/9233](https://forum.polygon.technology/t/snapshot-instructions-for-heimdall-and-bor/9233)

Thanks, Polygon Team

**Closed by ssandeep** 2022-06-28 20:14 UTC
