### ISSUE TITLE
Unexpected trx hashes in eth_getTransactionReceiptsByBlock

### ISSUE THREAD

**Issue by dsoldatow** [maticnetwork/bor#447] opened 2022-07-08 13:12 UTC
#### System information

Geth version: `0.2.14-stable-28963d5c`
OS & Version: Linux
Commit hash : 28963d5ccd3028e0ac6f1915845c747862d649d1
eth_getTransactionReceiptsByBlock with params: ["0x1cfe800"]

#### Expected behaviour
All transaction hashes exist in receipt objects

#### Actual behaviour
First receipt:
    "transactionHash": "0x615141657f68a41c33ae2ed087f38782812e1fc386aea0b8a51a88fbd0e86d47",
    "transactionIndex": "0x0"
Second receipt:
   "transactionHash": "0x615141657f68a41c33ae2ed087f38782812e1fc386aea0b8a51a88fbd0e86d47",
    "transactionIndex": "0x1"
Indexes are different, but hashes are the same

And in all receipts indexes are different, but hash only one.

Full response: [receipts.txt](https://github.com/maticnetwork/bor/files/9070408/receipts.txt)
#### Steps to reproduce the behaviour
curl --location --request POST 'NODE_URL' \
--header 'Content-Type: application/json' \
--data-raw '{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "eth_getTransactionReceiptsByBlock",
   "params": ["0x1cfe800"]
}'

I am writing to you on behalf of the [WatchData.io](https://watchdata.io) (blockchain data provider). We are adding polygon to our system now and this bug is important for us.

**Comment by dsoldatow** [comment] 2022-07-08 14:31
Ok. I will check, but not today

**Comment by kfastov** [comment] 2022-07-11 17:23
I found that if there is a "bor transaction" in a block, each transaction gets a hash of that bor transaction due to an error in the condition.
https://github.com/maticnetwork/bor/blob/04e90e2426ac257b7db812478d2370a8b8d0fab2/internal/ethapi/api.go#L683-L685

**Comment by dsoldatow** [comment] 2022-07-12 14:57
yeah, i tryed tag: 0.2.16 on commit hash: f083705e00b6497e575a6e6c800aad661a4a2eca and got the same.

**Comment by dsoldatow** [comment] 2022-07-19 12:19
Polygon API is available now on wachdata.io. @JekaMas, What about add WatchData.io to https://docs.polygon.technology/docs/develop/network-details/network/

**Comment by 0xKrishna** [comment] 2022-07-20 07:12
I think the issue is resolved, You can contact support team on discord for the above request, They will help you with that for sure.
Closing the issue for now.

**Closed by 0xKrishna** 2022-07-20 07:12 UTC
