### ISSUE TITLE
Bor stuck at **### Head state missing, repairing** for a long time

### ISSUE THREAD

**Issue by fwhappy** [maticnetwork/bor#191] opened 2021-09-17 02:06 UTC
#### System information

Geth version: `geth version`
Bor
```
Version: 1.10.8-stable
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/home/ubuntu/.g

```
OS & Version: Windows/Linux/OSX
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

```

I made an AMI with a running polygon node
Then I restarted a new instance from this AMI
After the heimdall sync completed, i started the bor service, but the logs stuck at **### Head state missing, repairing** for a long time and cannot start to sync

```
Sep 17 01:58:39 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:39.800] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: <nil>, Engine: bor}"
Sep 17 01:58:40 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:40.910] Gasprice oracle is ignoring threshold set threshold=2
Sep 17 01:58:40 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:40.911] Initialising Ethereum protocol           network=137 dbversion=8
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local header          number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local full block      number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local fast block      number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: WARN [09-17|01:58:41.062] Head state missing, repairing            number=19,159,921 hash=aa7907..5a3f89 snaproot=3e01c2..5d4453
```

**Comment by ssandeep** [comment] 2021-09-17 08:15
Please check if heimdall is running and in sync (ensure that heimdall block height is close to https://wallet.polygon.technology/staking/). Also, it takes a few hours to recover from "Head state missing" state.

**Comment by fwhappy** [comment] 2021-09-17 08:47
@ssandeep 
I'm sure heimdall's sync is complete
I spent more than 1 day, and it didn't finish Head state missing

**Comment by fwhappy** [comment] 2021-09-17 08:55
@ssandeep 

I can't get the polygon to sync right now
I have tried three ways

1. reboot from a crashed node to enable fast syncing 
`> eth.syncing
{
  currentBlock: 19198435,
  highestBlock: 19198531,
  knownStates: 423690946,
  pulledStates: 423614568,
  startingBlock: 19196298
}`
This went on for days and days and days, but it didn't sync successfully

2. I made ami from a node with normal sync, and after starting a new instance, it was in "Head state missing, repairing" and could not finish
`Sep 17 01:58:39 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:39.800] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: <nil>, Engine: bor}"
Sep 17 01:58:40 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:40.910] Gasprice oracle is ignoring threshold set threshold=2
Sep 17 01:58:40 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:40.911] Initialising Ethereum protocol           network=137 dbversion=8
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local header          number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local full block      number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: INFO [09-17|01:58:41.062] Loaded most recent local fast block      number=19,159,921 hash=aa7907..5a3f89 td=219,043,159 age=21h3m13s
Sep 17 01:58:41 ip-10-0-3-16 bash[86407]: WARN [09-17|01:58:41.062] Head state missing, repairing            number=19,159,921 hash=aa7907..5a3f89 snaproot=3e01c2..5d4453`

3. I opened a new node, after heimdall sync is done, bor can't connect to any peer, this state lasted for several days
`Sep 15 01:10:29 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:29.974] Looking for peers                        peercount=0 tried=189 static=66
Sep 15 01:10:35 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:10:35.439] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
Sep 15 01:10:40 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:40.297] Looking for peers                        peercount=0 tried=170 static=66
Sep 15 01:10:50 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:50.320] Looking for peers                        peercount=0 tried=85  static=66
Sep 15 01:10:53 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:10:53.344] Snapshot extension registration failed   peer=78e19f52 err="peer connected on snap without compatible eth support"
Sep 15 01:11:00 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:00.622] Looking for peers                        peercount=0 tried=83  static=66
Sep 15 01:11:03 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:03.577] deleteAllExpiredTxs                      total=0   expried=0 deleted=0
Sep 15 01:11:21 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:21.596] Looking for peers                        peercount=0 tried=33  static=66
Sep 15 01:11:21 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:11:21.598] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
Sep 15 01:11:32 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:32.986] Looking for peers                        peercount=0 tried=195 static=66
`

I have no other way out, I really need your help
Will upgrading the hardware help?

**Comment by ssandeep** [comment] 2021-09-17 09:21
What is your current hardware configuration? Generally, upgrading the volume (to gp3 on aws increasing the IOPS to 10000 makes the syncing fast).

**Comment by fwhappy** [comment] 2021-09-17 10:06
I'll start a node with IOPS=10K and try it.
What could be the reason for not connecting to any node?

**Comment by ssandeep** [comment] 2021-09-17 11:28
I am not sure, can you check your network/firewall settings? You are able to connect other nodes and not this, may be check the differences in the config, etc.

**Comment by fwhappy** [comment] 2021-09-17 11:36
This is the error in the bor log

`Sep 17 11:28:36 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:28:36.938] Snapshot extension registration failed   peer=e5f21886 err="peer connected on snap without compatible eth support"
Sep 17 11:30:10 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:30:10.884] Snapshot extension registration failed   peer=45d2cbc9 err="peer connected on snap without compatible eth support"
Sep 17 11:30:36 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:30:36.305] Snapshot extension registration failed   peer=df3c818f err="peer connected on snap without compatible eth support"
Sep 17 11:30:44 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:30:44.144] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
Sep 17 11:30:44 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:30:44.356] Snapshot extension registration failed   peer=c1bb7cc4 err="peer connected on snap without compatible eth support"
Sep 17 11:32:17 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:32:17.946] Snapshot extension registration failed   peer=c1bb7cc4 err="peer connected on snap without compatible eth support"
Sep 17 11:33:06 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:33:06.535] Snapshot extension registration failed   peer=63cbe74f err="peer connected on snap without compatible eth support"
Sep 17 11:33:15 matic-node-us2.techxmind.com bash[833390]: ERROR[09-17|11:33:15.827] Snapshot extension registration failed   peer=85f71f39 err="peer connected on snap without compatible eth support"`

Other nodes in the same security group are synchronized successfully
So it has nothing to do with firewall

**Comment by fwhappy** [comment] 2021-09-18 10:44
Hello, @ssandeep 

```
> eth.syncing
{
  currentBlock: 19201901,
  highestBlock: 19235723,
  knownStates: 416364,
  pulledStates: 161231,
  startingBlock: 18851531
}
```
How many States are there in total that need to be synchronized?
If the time is long enough, must it be possible to finish synchronization?

**Comment by fwhappy** [comment] 2021-09-18 11:15
@ssandeep 

I am using an AMI made from a running server

After a whole day of "Head state missing, repairing", I restarted bor service

Bor's syncmode was automatically changed from full to fast

I read Bor's code and found out that maybe the fullState is missing.

```
fullBlock, fastBlock := h.chain.CurrentBlock(), h.chain.CurrentFastBlock()
if fullBlock.NumberU64() == 0 && fastBlock.NumberU64() > 0 {
	h.fastSync = uint32(1)
	log.Warn("Switch sync mode from full sync to fast sync")
}
```

Would reapiring Head state cause this to happen?

**Comment by ssandeep** [comment] 2021-09-20 05:46
Let me check and get back to you.

**Comment by 0xKrishna** [comment] 2021-09-20 06:38
That is a warning that says to change, But it doesn't the mode actually automatically.
Regarding that gap of 64-128 blocks between current and highest, it's a known situation where your node is trying to fetch states, Explained here https://github.com/ethereum/go-ethereum/issues/16411#issuecomment-377176640
Check `eth.blockNumber` on your node, If that is 0 then either you can wait for states to sync (might take time since we have lot more txns that ethereum) , I suggest to use `syncmode snap` for this, Otherwise you can also try using lates snapshot (backup) from https://snapshots.matic.today/

Also, Head state repairing is caused by unclean shutdowns, Bor keeps recent blocks in memory for faster processing and when there is an unclean shutdown it's not able to persist those blocks into DB and have to repair. Sometimes it may take very long due to corrupted data as well. In general, this gets solved b/w 1min - 2 Hrs.

**Comment by 0xKrishna** [comment] 2021-09-28 07:06
@fwhappy Any update? Did the above solutions worked ?

**Comment by fwhappy** [comment] 2021-09-28 07:10
The problem is solved!
After heimdall finished syncing the city,
I downloaded the "Mainnet Pruned Bor snapshot" from https://snapshots.matic.today/ and was able to continue the sync, and now my node is working!
@0xKrishna  @ssandeep 

Thanks for your help!

**Comment by 0xKrishna** [comment] 2021-09-28 07:13
Okay, Thanks for the update, Closing the issue then.

**Closed by 0xKrishna** 2021-09-28 07:13 UTC

**Comment by MatheusMorozetti** [comment] 2022-06-08 15:06
> unclean

What is the best way to stop the bor service? I'm running in container and after some restart I came across the db corrupted error

**Comment by sylviahuang123** [comment] 2022-10-20 10:57
@fwhappy hello, can I ask you for help? how to solve this.
here is my heimdalld.log:
```
I[2022-10-20|10:49:07.568] Executed block                               module=state height=11338932 validTxs=0 invalidTxs=0
I[2022-10-20|10:49:07.583] Committed state                              module=state height=11338932 txs=0 appHash=E3C66C4F48694E3A3E7014E3384548CEFA8090D10288EE83EB2C4C7F6D85F458
E[2022-10-20|10:49:12.061] Stopping peer for error                      module=p2p peer="Peer{MConn{47.250.54.10:26656} 7ae8fda8f5eb092050f0e99e7bb80b792c5f4e12 out}" err=EOF
E[2022-10-20|10:49:12.080] Stopping peer for error                      module=p2p peer="Peer{MConn{147.139.208.251:26656} e8f5bd623345177d0e177f13bec1daa67b5462de out}" err=EOF
E[2022-10-20|10:49:12.113] Stopping peer for error                      module=p2p peer="Peer{MConn{149.129.216.188:26656} ba769bfddb45489573f07e311aa742d40163d0e1 out}" err=EOF
E[2022-10-20|10:49:12.337] Stopping peer for error                      module=p2p peer="Peer{MConn{8.211.130.206:26656} 2bafff07b9fc02ab1a92fe6539a8f41a7679076a out}" err=EOF
E[2022-10-20|10:49:12.381] Stopping peer for error                      module=p2p peer="Peer{MConn{47.245.53.139:26656} 6b15e046fd4ef3d82073cf2e46f663a030fdcfd0 out}" err=EOF
E[2022-10-20|10:49:12.503] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.16.203:26656} 5d835437973a542cc98cf253679ee156df9efcd9 out}" err=EOF
E[2022-10-20|10:49:12.582] Stopping peer for error                      module=p2p peer="Peer{MConn{37.120.245.165:26656} 2d5bfa7d16a26d058344691df21c39067022afa2 out}" err=EOF
E[2022-10-20|10:49:12.665] Stopping peer for error                      module=p2p peer="Peer{MConn{54.211.41.134:26656} f1df2b5ecb85112a91da6d8caa76d9dd22fdd4cf out}" err=EOF
E[2022-10-20|10:49:12.673] Stopping peer for error                      module=p2p peer="Peer{MConn{18.233.245.160:26656} 7984299ef8e129ae84c693b6c27236cc0e900d7d out}" err=EOF
E[2022-10-20|10:49:12.690] Failed Sanity Check! Cant add old address to new bucket module=p2p book=/data/polygon/heimdall/config/addrbook.json ka="&{Addr:3277d77ded24aee8d54112ececfd37af18ecbc08@93.115.28.53:26656 Src:7ae8fda8f5eb092050f0e99e7bb80b792c5f4e12@0.0.0.0:26656 Attempts:9 LastAttempt:2022-09-16 08:19:43.039166555 +0000 UTC m=+3905792.338276089 LastSuccess:2022-07-13 05:36:50.19375599 +0000 UTC BucketType:2 Buckets:[32]}" bucket=51
E[2022-10-20|10:49:12.708] Stopping peer for error                      module=p2p peer="Peer{MConn{35.199.4.13:26656} 2eadba4be3ce47ac8db0a3538cb923b57b41c927 out}" err=EOF
E[2022-10-20|10:49:12.760] Stopping peer for error                      module=p2p peer="Peer{MConn{15.235.14.28:26656} 19d0adc936984d10e97ace0aa8477d8c960ebe32 out}" err=EOF
E[2022-10-20|10:49:12.773] Stopping peer for error                      module=p2p peer="Peer{MConn{192.41.77.211:26656} baaeabfdb0a3a1d528cc116c502d8c5d39b4bb64 out}" err=EOF
E[2022-10-20|10:49:12.814] Stopping peer for error                      module=p2p peer="Peer{MConn{18.197.47.24:26656} 6eaa6013f357e88fa83330df6e94563edc8b87b5 out}" err=EOF
E[2022-10-20|10:49:13.004] Stopping peer for error                      module=p2p peer="Peer{MConn{18.228.98.237:26656} afc41bd37d549186cec915c5a4feb3071871cdc1 out}" err=EOF
E[2022-10-20|10:49:13.006] Stopping peer for error                      module=p2p peer="Peer{MConn{177.71.163.170:26656} 48daf8805cc572ff555889e8e361768542e3314b out}" err=EOF
```
here is my bor.log
```
INFO [10-20|10:43:09.049] Allocated cache and file handles         database=/data/polygon/bor/bor/chaindata cache=512.00MiB handles=51200
INFO [10-20|10:43:27.723] Opened ancient database                  database=/data/polygon/bor/bor/chaindata/ancient readonly=false
INFO [10-20|10:43:27.739] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}"
INFO [10-20|10:43:47.741] Gasprice oracle is ignoring threshold set threshold=2
INFO [10-20|10:43:47.748] Initialising Ethereum protocol           network=137 dbversion=8
INFO [10-20|10:43:50.263] Loaded most recent local header          number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.264] Loaded most recent local full block      number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.264] Loaded most recent local fast block      number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.271] Loaded last fast-sync pivot marker       number=21,075,478
WARN [10-20|10:43:50.274] Head state missing, repairing            number=34,535,308 hash=99f908..e149f6 snaproot=6e0df3..fe238e
```
I wonder is it normal? And you said download `Mainnet Pruned Bor snapshot` how to install and something to do? Can you tell me detail? Many thanks.
