### ISSUE TITLE
Eth to polygon pos bridge not working as expected

### ISSUE THREAD

**Issue by imom0** [maticnetwork/bor#1244] opened 2024-05-09 02:34 UTC
I sent some $DATA to polygon bridge

https://etherscan.io/token/0x8f693ca8d21b157107184d29d398a8d082b38b76?a=0x826a4f4da02588737d3c27325b14f39b5151ca3c

BUT NOT RECEIVED ANY TOKENS ON POLYGON

https://polygonscan.com/token/0x3a9a81d576d83ff21f26f325066054540720fc34?a=0x826A4f4DA02588737d3c27325B14F39b5151CA3C

it has been a long time... is there a problem with the bridge or token?other tokens are bridged OK.

**Comment by temaniarpit27** [comment] 2024-05-09 18:44
Please send txn details which was performed

**Comment by imom0** [comment] 2024-05-09 22:36
> Please send txn details which was performed

https://etherscan.io/tx/0x20b5e53a03570f0e0c574f57b67a018a7818450a467f298feef7eae2133c8351

and 

https://etherscan.io/tx/0xe063fe5b017bea36a1e22c47a23d76a2b0146beb1c70461abbb75212c3412875

all call 0xa0c68c638235ee32657e8f720a23cec1bfc77c77(Polygon (Matic): Bridge) **depositFor** in the end, calldata like 

`0xe3dec8fb000000000000000000000000826a4f4da02588737d3c27325b14f39b5151ca3c0000000000000000000000008f693ca8d21b157107184d29d398a8d082b38b76000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000006538b27ed3c1c90f0e1`

**Comment by imom0** [comment] 2024-05-21 07:15
> Please send txn details which was performed

@temaniarpit27 another eth to polygon case, did not received YUP token after an hour 

https://etherscan.io/tx/0x66374b1ac649d731ad22468c01abb8ab21b33454bf49bff64d05c0f96f73abf0

https://polygonscan.com/token/0x086373fad3447f7f86252fb59d56107e9e0faafa?a=0x826a4f4da02588737d3c27325b14f39b5151ca3c

**Comment by DhairyaSethi** [comment] 2024-05-29 09:26
| txn                                                                                                        | corresponding state sync                                                                                               | log index | reason                                                                                                                                                                                                                                                                                                                                                      | sim                                                                                |
|------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|-----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|
| [0x20b...351](https://etherscan.io/tx/0x20b5e53a03570f0e0c574f57b67a018a7818450a467f298feef7eae2133c8351)  | [0x4d50...f81](https://polygonscan.com/tx/0x4d50da36af85bded20cc82c7a696819282837b5b76c846dbd81fbac4cde97f81#eventlog) | 712       | the [token](https://polygonscan.com/address/0x3a9a81d576d83ff21f26f325066054540720fc34#code) has a receive hook (DATAv2#1227) on pos which is called on all transfers, and the [receiver](https://polygonscan.com/address/0x826a4f4da02588737d3c27325b14f39b5151ca3c) (unverified) is a contract which reverts on this hook; hence reverting the state sync | [link](https://www.tdly.co/shared/simulation/cfd8a9bf-c0cb-484f-9828-8ed430134ccd) |

**Comment by imom0** [comment] 2024-05-29 13:10
> txn	corresponding state sync	log index	reason	sim
> [0x20b...351](https://etherscan.io/tx/0x20b5e53a03570f0e0c574f57b67a018a7818450a467f298feef7eae2133c8351)	[0x4d50...f81](https://polygonscan.com/tx/0x4d50da36af85bded20cc82c7a696819282837b5b76c846dbd81fbac4cde97f81#eventlog)	712	the [token](https://polygonscan.com/address/0x3a9a81d576d83ff21f26f325066054540720fc34#code) has a receive hook (DATAv2#1227) on pos which is called on all transfers, and the [receiver](https://polygonscan.com/address/0x826a4f4da02588737d3c27325b14f39b5151ca3c) (unverified) is a contract which reverts on this hook; hence reverting the state sync	[link](https://www.tdly.co/shared/simulation/cfd8a9bf-c0cb-484f-9828-8ed430134ccd)

is there  a way I can withdraw these tokens?

**Comment by DhairyaSethi** [comment] 2024-05-29 14:25
> is there  a way I can withdraw these tokens?

there's [PIP36](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-36.md) in the peer review stage which adds the ability to replay these failed state syncs, if you have access to the receiver src, & can make it succeed on the token transfer callback - you'll be able withdraw the tokens if the PIP goes live. currently, replaying failed state syncs is not possible.

**Comment by imom0** [comment] 2024-05-29 23:53
> > Please send txn details which was performed
> 
> 
> 
> @temaniarpit27 another eth to polygon case, did not received YUP token after an hour 
> 
> 
> 
> https://etherscan.io/tx/0x66374b1ac649d731ad22468c01abb8ab21b33454bf49bff64d05c0f96f73abf0
> 
> 
> 
> https://polygonscan.com/token/0x086373fad3447f7f86252fb59d56107e9e0faafa?a=0x826a4f4da02588737d3c27325b14f39b5151ca3c

@DhairyaSethi have you inspected this case, the bridge has succeeded before.

**Comment by imom0** [comment] 2024-06-14 16:22
> This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 14 days.

**Comment by imom0** [comment] 2024-06-30 00:33
> This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 14 days.

**Comment by imom0** [comment] 2024-07-16 02:15
still not resolved

**Comment by DhairyaSethi** [comment] 2024-07-16 03:22
hi! apologies for the late reply, the issue with the second [token](https://polygonscan.com/token/0x086373fad3447f7f86252fb59d56107e9e0faafa?a=0x826a4f4da02588737d3c27325b14f39b5151ca3c#readProxyContract#F10) is that the admin has unset the DEPOSITOR_ROLE for [childChain](https://polygonscan.com/address/0xD9c7C4ED4B66858301D0cb28Cc88bf655Fe34861#code) - this is required for all tokens to mint locked supply during the bridge txn, due to this the above state syncs have failed. our team is trying to get in touch with the authors to remedy the above, it's been blocked on the UI since this issue was opened meanwhile.

**Comment by imom0** [comment] 2024-08-08 06:50
> hi! apologies for the late reply, the issue with the second [token](https://polygonscan.com/token/0x086373fad3447f7f86252fb59d56107e9e0faafa?a=0x826a4f4da02588737d3c27325b14f39b5151ca3c#readProxyContract#F10) is that the admin has unset the DEPOSITOR_ROLE for [childChain](https://polygonscan.com/address/0xD9c7C4ED4B66858301D0cb28Cc88bf655Fe34861#code) - this is required for all tokens to mint locked supply during the bridge txn, due to this the above state syncs have failed. our team is trying to get in touch with the authors to remedy the above, it's been blocked on the UI since this issue was opened meanwhile.

https://etherscan.io/tx/0x67827b42623482a95949a8a1975a8f06a5942f987adba801c55a339a5d4cc154

the same issue occurs with new token PERI

**Comment by DhairyaSethi** [comment] 2024-08-11 21:14
the state syncs revert here due to incorrect bridge params set by the token owner ([incorrect child chain manager](https://polygonscan.com/address/0x8f151e700772d6e8Dc7dA8B260c9e0C3eCbF4174#readContract#F9), currently set to 0x981Ca3e19AB02f758f252611bb5881AA4ECEDB3B)

**Comment by Raneet10** [comment] 2024-08-22 04:13
Looks like we've reached the root cause. I'm closing this for now but feel free to open again in case I'm mistaken. Thanks!

**Closed by Raneet10** 2024-08-22 04:13 UTC
